replicaCount: 1

frontend:
  image:
    repository: ghcr.io/hermanvulkers/k8s-microblog-frontend
    tag: latest
  imagePullPolicy: Always
  service:
    port: 80

backend:
  image:
    repository: ghcr.io/hermanvulkers/k8s-microblog-backend
    tag: latest
  imagePullPolicy: Always
  service:
    port: 3000
  kafkaBroker: my-cluster-kafka-bootstrap.kafka.svc:9092

