apiVersion: v1
kind: Service
metadata:
  name: microblog-backend
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-resource-group: microblog-rg
    service.beta.kubernetes.io/azure-load-balancer-ip: 132.220.176.92
spec:
  type: LoadBalancer
  selector:
    app: microblog-backend
  ports:
    - protocol: TCP
      port: {{ .Values.backend.service.port }}
      targetPort: 3000
